(ns language.esmx)


(def lines
  {;29 Apr 2021
   "Currency" "Moneda"

   ;settings
   "General Settings" "Ajustes generales"
   "Brand Name" "Marca"
   "Your company / brand name" "Nombre de su empresa/marca"
   "Legal Company Name" "Nombre de la empresa en la factura"
   "Tax Authority" "Autoridad Fiscal"
   "Tax Number" "Código de identificación fiscal"
   "Email" "Email"
   "Region" "Región"
   "City" "Ciudad"
   "Company Location" "Dirección de empresa"
   "Phones" "Teléfonos"
   "Delivering" "Entregas"
   "Open" "Abrir"
   "Close" "Cerrar"
   "Customer Phones" "Teléfonos de clientes"
   "Hidden" "Ocultar" ; 
   "Visible" "Mostrar"
   "Sending SMS" "Enviar SMS"
   "IVR Type" "Tipo de IVR"
   "Not available" "No disponible"
   "Repeating order" "Pedido recurrente"
   "Product amount" "Cantidad de producto"
   "Language" "Idioma"
   "Other Settings" "Ajustes adicionales"
   "User Accounts" "Cuentas de usuarios"
   "Delivery Zones" "Zonas de entrega"
   "Brand Settings" "Ajustes de marca"
   "API Settings" "Ajustes de interfaz"
   "Telsam Settings" "Ajustes de Telsam"
   "SMS Contents" "Contenido de SMS"
   ;settings.cljs/delivery areas
   "Zone Name" "Nombre de zona"
   "All Subscribers" "Todos los abonados"
   "Red Zone" "Zona roja"
   "Blue Zone" "Zona azul"
   "Yellow Zone" "Zona amarilla"
   "Zone" "Zona"
   "Add" "Añadir"
   ;"Delete" "Sil"
   "All accounts without assigned delivery area will be automatically assigned to the first one." "Todas las cuentas que no tengan asignada una zona de entrega se asignarán automáticamente a la primera zona."

   ;Right Column
   "Workload" "Ejecución de pedidos"
   "Today's orders" "Pedidos de hoy"
   "Scheduled" "Pendientes"
   "Overdue" "Atrasados"
   "Completed" "Finalizados"
   "User: " "Usuario: "

   ;Navbar
   ;"User: " "Kullanıcı: "
   "Restart the app" "Reiniciar la aplicación"
   "Secure log-out" "Logout seguro"
   "Main" "Inicio"
   "New Account" "Nueva cuenta"
   "Account" "Cuenta"
   "Accounts" "Cuentas"
   "All Accounts" "Todas las cuentas"
   "Inventory" "Inventario"
   "Storages" "Almacenes"
   "Products" "Productos"
   "Carriers" "Transportistas"
   "Invoice" "Factura"
   "Accountancy" "Contabilidad"
   "Make a payment" "Pagar"
   "Get a payment" "Recibir dinero"
   "Reports" "Reportes"

   ;smartbox
   "Search" "Buscar"
   "New Order" "Nuevo pedido"

   ;order
   "Unassigned" "Nieprzypisane"
   "Debit" "Deber"
   "Credit" "Haber"
   "Filters" "Filtros"
   "My orders" "Mis pedidos"
   "Unassigned orders" "Pedidos no asignados"
   "Hide delivered" "Esconder pedidos entregados"
   "Show delviered" "Mostrar pedidos entregados"
   "Details" "Detalles"
   ;"Products" "Ürünler"
   "Carrier" "Transportista"
   ;...
   ;"Account" "Abone"
   "Schedule delivery" "Planificar entrega"
   "Now" "Ahora"
   "Order note" "Comentario de pedido"
   "Addition/Discount" "Pago adicional/Descuento"
   "Total: " "Total: "
   "Save" "Guardar"
   ;"Close" "Cerrar"

   ;employee status
   "delivering" "en reparto"
   "on-duty" "disponible"
   "break" "descanso"
   "offline" "no disponible"

   ;Accounts
   "Please provide a name" "Indique un nombre"
   "Wrong location format" "Formato de dirección incorrecto"
   "Please provide a phone number" "Indique un número de teléfono"
   "Phone number must be 10 digits" "El número de teléfono debe tener 10 dígitos"
   "Account Name" "Nombre de cuenta"
   "Tax ID" "Código de identificación fiscal"
   ;"Tax Authority" "Vergi Dairesi"
   ;"Invoice Address" "Fatura Adresi"
   "Account ID" "ID de la cuenta"
   "It will be assigned automatically" "Se asignará automáticamente."
   "IMPORTANT: Please don't use this area without consulting us." "IMPORTANTE: No utilice esta sección sin consultarnos."
   "If you leave empty a number will be assigned"  "Si lo deja vacío se le asignará un número."
   "If you leave this field empty, a number will be assigned"  "Si deja este campo vacío, se le asignará un número."
   "Name & Surname or Business Name" "Nombre y Apellido o Nombre de la Empresa"
   "Note (displayed next to the name)" "Comentario (Aparece junto al nombre)"
   "Receipt or Invoice" "Recibo/Factura"
   "Receipt" "Recibo"
   ;"Invoice" "Fatura"
   "IVR Orders" "Pedidos telefónicos"
   "If this is closed, the user cannot place order via IVR." "Si este campo está cerrado, la función de pedido telefónico no está disponible."
   ;"Open" "Açık"
   "Closed" "Cerrado"
   "Delivery Area" "Zona de entrega"
   "Neighbourhood" "Barrio"
   "Street Name" "Calle"
   "Building" "Apartamento/Casa"
   "Address Details" "Detalles de la dirección"
   "Sales Promotions" "Promociones de venta"
   "Apply" "Aplicar"
   "Don't Apply" "No aplicar"
   "Special Discounts" "Descuentos especiales"
   "Delivery Location" "Dirección de entrega"
   ;"Phones" "Telefonlar"
   "Rented Equipment" "Equipo prestado"
   "Notes" "Comentarios"
   "Archived" "Archivados"
   "Yes" "Sí"
   "No" "No"
   "Invoice Information" "Información de factura"
   "Bank Account" "Cuenta bancaria"
   "The record has been archived!" "¡El registro ha sido archivado!"
   "Successfully saved!" "¡Guardado correctamente!"
   "Save another record" "Guarda otro registro"
   ;"Save" "Kaydet"
   ;"New Account" "Yeni Hesap"
   ;"Account:" "Hesap"

   ; ---customertable.cljs
   "Paid back to the customer" "Reembolsado al cliente"
   "Customer paid towards debt" "El cliente ha pagado la deuda"
   "Debtors" "Deudores"
   "Creditors" "Acreedores"
   ;"Lent Equipment" "Emanet Alanlar"
   "Active Accounts" "Cuentas activas"
   "Archived Accounts" "Cuentas archivadas"
   ;"Account" "Abone"
   "Latest Order" "Últimos pedidos"
   "Address" "Dirección"
   ;"Notes" "Notlar"
   "Export" "Exportar"

  ;Employee.cljs
   "Plase enter a name" "Inserte el nombre"
   "Minimum 3 characters" "Mínimo 3 caracteres"
   "Name & surname" "Nombre y apellido"
   "Phone" "Teléfono"
   "Color" "Color"
   "Status" "Estado"
   "Assigned Storage" "Almacén/coche asignado"
   "New Carrier" "Nuevo transportista"
   "Carrier:"  "Transportista:"
   "Quick ledger record" "Registro contable rápido"

   ;Inventory.cljs
   "Item Name" "Nombre del artículo"
   ;"Details" "Detaylar"
   "Item Code" "Código del artículo"
   "Auto-assignment" "Asignación automática"
   "If you leave it empty a number will be assigned" "Si lo deja vacío se le asignará un número."
   ;"Color" "Renk"
   "Track Returnables" "Seguimiento de los artículos retornables"
   "If you want to track returnables choose 'Yes'. Once it's chosen it can't be changed later!" "Si desea hacer un seguimiento de los equipos prestados a los clientes, seleccione 'Sí'. Importante: esta opción no se puede modificar posteriormente."
   "Sellable Item" "Artículo para vender"
   "Nonsellable items can be tracked. Customers can't see them." "Los artículos que no se pueden vender pueden ser rastreados. Los clientes no pueden verlos."
   "Price with VAT" "Precio con IVA"
   "VAT" "IVA"
   "Price without VAT" "Precio sin IVA"
   "Returnable" "Retornable"
   "New Item" "Nuevo artículo"
   "Item" "articúlo"

   ;Search 
   "Order History" "Historial de pedidos"
   ;"Make a payment" "Ödeme yap"
   ;"Get a payment" "Ödeme al"
   "Edit" "Editar"
   ;Order history


   ;Order pop-up
   "Balance»customer" "Saldo"
   "Scheduled Delivery" "Pedidos pendientes"
   "Notes»order" "Comentarios"
   ;"Products" "Ürünler"
   "Service Fee" "Cuota de servicio"
   "Discount" "Descuento"
   "Order ID" "ID de pedido"
   ;"Carrier" "Plasiyer"
   ;"Unassigned" "Belirlenmedi"
   "This order is assigned to someone else." "Este pedido está asignado a otra cuenta."

   "I have delivered the items" "He entregado los artículos"
   "I have collected containers" "He recogido los recipientes vacíos"
   "I have collected the payment" "He recibido el pago"
   "Not enough products in the storage" "Falta de productos en el almacén"
   "Payer" "Pagador"
   "Payee" "Beneficiario"

   ;Next two lines will be recorded to storage history 
   "Order delivery" "Entrega de pedido"
   "Collected containers" "Recipientes recogidos"

   "Payment Amount" "Importe"
   "Items have been delivered" "Los artículos han sido entregados"
   "Containers have been collected" "Los recipientes se han recogido"
   "Payment has been collected" "Se ha cobrado el pago"

   "Cash Account" "Caja"

   "Changed»order" "Modificado"
   "Completed orders cannot be changed." "Los pedidos finalizados no se pueden modificar."
   "Save Changes" "Guardar cambios"

   "Total" "Total"
   "Total Price" "Precio total"

   ;phone & mixed.cljs
   "Call via IVR" "Llamar por IVR"
   "Call" "Llamar"
   "Calling..." "Llamando"
   "Delete Record" "Borrar registro"
   "Delete" "Borrar"
   "Cancel Deletion" "Cancelar la eliminación"
   "Wrong format" "Formato incorrecto"

   ;Warehouse.cljs
   ;"Plase enter a name" "İsim girilmelidir"
   ;"Color" "Renk"
   ;"Notes" "Notlar"
   ;"Save" "Kaydet"
   ;"Notes" "Notlar"
   ;"Target Storage" "Hedef Depo"
   ;"Notes" "Notlar"
   ;"Save" "Kaydet"
   "Storage Name" "Nombre del almacén"
   "Storage Type" "Tipo de almacén"
   "Vehicle" "Vehículo"
   "Warehouse" "Depósito"
   "Storage Manager" "Gestor de almacén"
   "Source Storage" "Almacén de origen"
   "Target Storage" "Almacén de destino"
   "Source" "Origen"
   "Target" "Destino"
   "Items" "Artículos"
   "Add New Storage" "Añadir nuevo almacén"
   "Add Items" "Añadir artículos"
   "Move Items" "Mover artículos"
   "Remove Items" "Borrar artículos"
   "Move items to another storage" "Mover artículos a otro almacén"
   "Storage" "Almacén"
   "Move" "Mover"

   ;Ledger.cljs
   ;"Source" "Kaynak"
   ;"Target" "Hedef"
   ;"Save" "Kaydet"
   "Saved" "Guardado"
   "This area is mandatory" "Este campo es obligatorio"
   "Please select" "Seleccione"
   "Enter the value" "Introduzca el valor"
   "Add a transaction" "Añadir una transacción"
   "Transaction reference" "Referencia de la transacción"
   "Transaction date" "Fecha de la transacción"
   ;"Now" "Şimdi"
   "Value" "Valor"
   "Date" "Fecha"
   ;"Account" "Hesap"
   "Start date" "Fecha de inicio"
   "End date" "Fecha de finalización"
   ;"Apply" "Uygula"
   "Transaction" "Transacción"
   "Transactions Filter" "Filtrar transacciones"
   "Past 5 weeks" "Últimas 5 semanas"
   "Filtered transactions" "Transacciones filtradas"
   "New Transaction" "Nueva transacción"


   ;users.cljs
   ;"Carrier" "Plasiyer"
   "Username" "Nombre de usuario"
   "Password" "Contraseña"
   "Manager" "Gerente"
   "Name" "Nombre"
   "User" "Usuario"
   "Permissions" "Permisos"
   "Add a new account" "Añadir una nueva cuenta"

   ;Time.cljs
   "January" "Enero"
   "February" "Febrero"
   "March" "Marzo"
   "April" "Abril"
   "May " "Mayo"
   "June" "Junio"
   "July" "Julio"
   "August" "Agosto"
   "September" "Septiembre"
   "October" "Octubre"
   "November" "Noviembre"
   "December" "Diciembre"

   "Jan" "en."
   "Feb" "febr."
   "Mar" "mzo."
   "Apr" "abr."
   "May" "my"
   "Jun" "jun."
   "Jul" "jul."
   "Agu" "ag."
   "Sep" "sept."
   "Oct" "oct."
   "Nov" "nov."
   "Dec" "dic."

   "Monday" "Lunes"
   "Tuesday" "Martes"
   "Wednesday" "Miércoles"
   "Thursday" "Jueves"
   "Friday" "Viernes"
   "Saturday" "Sábado"
   "Sunday" "Domingo"

   "minutes" "minutos"
   "hours" "horas"
   "days" "días"
   "months" "meses"
   "ago" "atrás"
   "later" "después"})

; END OF THE FILE
; Ignore everthing after this point

(def blocks
  {:settings-top
   [:<>
    [:h4 "Önemli Not:"]
    [:p "Türkçe içerik" [:strong " datanız kaybolur."] " Dropbox ile bağlanın"]
    [:p "Şunu kullanıyoruz " [:a {:href "https://remotestorage.io/"} "remotestorage.io"] " protokolle bağlanın."]]})