(ns language.ptbr)

(def lines
  {;25 Jul 2021
   "Organization Account" "Nome da Empresa"
   ;"Username" "Nome do Usuário"
   ;"Password" "Senha"
   "Your password is saved!"  "Sua senha está salva"
   "Remember me" "Esqueci a Senha"
   "Sign In" "Log in"
   "Please enter organization account"   "Por favor entre na conta da empresa"
   "Plase enter account information" "Por favor, insira as informações da conta"

   ;27 Jun 2021
   "Amount" "Quantidade"
   "Phone number must contain 7 to 11 digits." "O número de telefone deve conter de 7 a 11 dígitos."

   ;29 Apr 2021
   "Currency" "Currency"
   "Unknown Number" "Unknown Number"
   
   ;settings
   "General Settings" "Configurações gerais"
   "Brand Name" "Marca"
   "Your company / brand name" "Sua empresa/marca"
   "Company invoice name" "Nome da empresa"
   "Tax Authority" "Órgão de imposto"
   "Tax Number" "Número do imposto"
   "Invoice Address" "Endereço da fatura"
   "E-mail" "E-mail"
   "City" "Estado"
   "Town" "Cidade"
   "Company Location" "Endereço da empresa"
   "Phones" "Telefones"
   "Order Status" "Status do pedido"
   "Open" "Abrir"
   "Close" "Fechar"
   "Customer Phones" "Telefones do cliente"
   "Hidden" "Escondido"
   "Visible" "Visível"
   "Sending SMS" "Enviando SMS"
   "IVR Type" "Chamada URA"
   "Not available" "Indisponível"
   "Repeating order" "Repetindo o pedido"
   "Product amount" "Quantidade do produto"
   "Language" "Idioma"
   "Other Settings" "Outras configurações"
   "User Accounts" "Contas do usuário"
   "Delivery Zones" "Zonas de entrega"
   "Brand Settings" "Definições da marca"
   "API Settings" "Configurações da Interface"
   "Telsam Settings" "Configurações Telsam"
   "SMS Contents" "Conteúdo SMS"
   ;settings.cljs/delivery areas
   "Zone Name" "Nome da zona"
   "All Subscribers" "Todos assinantes"
   "Red Zone" "Zona vermelha"
   "Blue Zone" "Zona azul"
   "Yellow Zone" "Zona amarela"
   "Zone" "Zona"
   "Add" "Adicionar"
   ;"Delete" "Sil"
   "All accounts without assigned delivery area will be automatically assigned to the first one." "Todas as contas sem zona de entrega definida serão automaticamente adicionadas à primeira zona"

   ;Right Column
   "Workload" "Trabalho em progresso"
   "Today's orders" "Pedidos de hoje"
   "Scheduled" "Agendados"
   "Overdue" "Atrasados"
   "Completed" "Finalizados"
   "User: " "Usuário: "

   ;Navbar
   ;"User: " "Kullanıcı: "
   "Restart the app" "Reiniciar aplicativo"
   "Secure log-out" "Logout seguro"
   "Operation" "Operações"
   "New Account" "Nova conta"
   "Account" "Conta"
   "Accounts" "Contas"
   "All Accounts" "Todas as contas"
   "Inventory" "Inventário"
   "Storages" "Armazém"
   "Products" "Produtos"
   "Carriers" "Entregadores"
   "Invoice" "Fatura"
   "Accountancy" "Contabilidade"
   "Make a payment" "Transferir dinheiro"
   "Get a payment" "Receber dinheiro"
   "Reports" "Relatórios"

   ;smartbox
   "Search" "Pesquisar"
   "New Order" "Novo pedido"

   ;order
   "Unassigned" "Aguardando"
   "Debit" "Débito"
   "Credit" "Crédito"
   "Filters" "Filtros"
   "My orders" "Meus pedidos"
   "Unassigned orders" "Pedidos aguardando"
   "Hide delivered" "Esconder pedidos entregues"
   "Show delviered" "Mostrar pedidos entregues"
   "Details" "Detalhes"
   ;"Products" "Ürünler"
   "Carrier" "Entregador"
   ;...
   ;"Account" "Abone"
   "Schedule order" "Agendar pedido"
   "Now" "Agora"
   "Order note" "Comentário do pedido"
   "Addition/Discount" "Pagamento adicional/Disconto"
   "Total: " "Total: "
   "Save" "Salvar"
   ;"Close" "Fechar"

   ;employee status
   "delivering" "Entregando"
   "on-duty" "Disponível"
   "break" "Intervalo"
   "offline" "Indisponível"

   ;Accounts
   "Please provide a name" "Insira o nome"
   "Wrong location format" "Endereço incorreto"
   "Please provide a phone number" "Insira um número de telefone"
   "Phone number must be 10 digits" "Número de telefone deve conter 10 dígitos"
   "Account Name" "Nome da conta"
   "Tax ID" "Número de Identificação Fiscal"
   ;"Tax Authority" "Vergi Dairesi"
   ;"Invoice Address" "Fatura Adresi"
   "Account ID" "ID da conta"
   "It will be assigned automatically" "Será gerado automaticamente"
   "IMPORTANT: Please don't use this area without consulting us." "ATENÇÂO: Por favor, não use esta função sem nos consultar."
   "If you leave empty a number will be assigned"  "Caso não preencher este campo, será gerado um número."
   "Name & Surname or Business Name" "Nome e sobrenome ou nome da empresa"
   "Note (Displays next to the name)" "Comentário (será visualisado ao lado do sobrenome)"
   "Receipt or Invoice" "Comprovante/Fatura"
   "Receipt" "Comprovante"
   ;"Invoice" "Fatura"
   "IVR Orders" "Pedidos URA"
   "If this is closed, the user cannot place order via IVR." "Caso esteja desativado, o usuário não pode fazer pedido por URA"
   ;"Open" "Açık"
   "Closed" "Fechado"
   "Delivery Area" "Área de entrega"
   "Neighbourhood" "Bairro"
   "Street Name" "Rua/Apartamento/Casa"
   "Building" "Cidade"
   "Address Details" "Complemento do endereço"
   "Sales Promotions" "Promoções de venda"
   "Apply" "Aplicar"
   "Don't Apply" "Não aplique"
   "Special Discounts" "Descontos especiáis"
   "Delivery Location" "Localização da entrega"
   ;"Phones" "Telefonlar"
   "Lent Equipment" "Equipamento imprestado"
   "Notes" "Comentários"
   "Archived" "Arquivados"
   "Yes" "Sim"
   "No" "Não"
   "Invoice Information" "Informação de fatura"
   "Bank Account" "Conta do banco"
   "The record has been archived!" "O registro foi arquivado!"
   "Successfully saved!" "Salvo com sucesso!"
   "Save another record" "Salva outro registro"
   ;"Save" "Kaydet"
   ;"New Account" "Yeni Hesap"
   ;"Account:" "Hesap"

   ; ---customertable.cljs
   "Paid back to the customer" "Pago de volta ao cliente"
   "Customer paid towards debt" "O cliente pagou parte do crédito"
   "Debtors" "Devedores"
   "Creditors" "Credores"
   ;"Lent Equipment" "Emanet Alanlar"
   "Active Accounts" "Contas ativas"
   "Archived Accounts" "Contas arquivadas"
   ;"Account" "Abone"
   "Latest Order" "Último pedido"
   "Address" "Endereço"
   ;"Notes" "Notlar"
   "Export" "Exportar"

  ;Employee.cljs
   "Plase enter a name" "Insira o nome"
   "Minimum 3 characters" "Mínimo 3 caracteres"
   "Carrier Name & Surname" "Nome do entregador"
   "Phone" "Telefone"
   "Color" "Cor"
   "Status" "Status"
   "Assigned to Storage" "Armazenado"
   "New Carrier" "Novo entregador"
   "Carrier:"  "Entregador:"
   "Quick ledger record" "Relatório contábil rápido"

   ;Inventory.cljs
   "Item Name" "Nome do item"
   ;"Details" "Detaylar"
   "Item Code" "Código do item"
   "Auto-assignment" "Auto-atribuído"
   "If you leave it empty a number will be assigned" "Caso não preencher este campo, será gerado um número."
   ;"Color" "Renk"
   "Track Returnables" "Rastrear equipamento retornável"
   "If you want to track returnables choose 'Yes'. Once it's chosen it can't be changed later!" "Se você quer rastrear equipamento retornável, escolha 'Sim'. Uma vez escolhido, não pode ser alterado!"
   "Sellable Item" "Item para vender"
   "Nonsellable items can be tracked. Customers can't see them." "Itens indisponíveis para venda podem ser rastreados. Não são visíveis para os clientes."
   "Price with VAT" "Preço com taxa"
   "VAT" "Taxa"
   "Price without VAT" "Preço sem taxa"
   "Returnable" "Retornável"
   "New Item" "Novo item"
   "Item" "Item"

   ;Search 
   "Order History" "Histórico de pedidos"
   ;"Make a payment" "Ödeme yap"
   ;"Get a payment" "Ödeme al"
   "Edit" "Editar"
   ;Order history


   ;Order pop-up
   "Balance»customer" "Saldo em conta"
   "Scheduled Delivery" "Entrega agendada"
   "Notes»order" "Comentários"
   ;"Products" "Ürünler"
   "Service Fee" "Taxa de serviço"
   "Discount" "Disconto"
   "Order ID" "ID do pedido"
   ;"Carrier" "Plasiyer"
   ;"Unassigned" "Belirlenmedi"
   "This order is assigned to someone else." "Este pedido foi atribuído a outra pessoa."

   "I have delivered the items" "Entreguei os itens"
   "I have collected containers" "Coletei os recipientes"
   "I have collected the payment" "Recebi o pagamento"
   "Not enough products in the storage" "Produtos insuficientes no armazém"
   "Payer" "Pagador"
   "Payee" "Beneficiário"

   ;Next two lines will be recorded to storage history 
   "Order delivery" "Entrega do pedido"
   "Collected containers" "Recipientes coletados"

   "Payment Amount" "Valor do pagamento"
   "Items have been delivered" "Os itens foram entregues"
   "Containers have been collected"    "Os recipientes foram coletados"
   "Payment has been collected" "O pagamento foi recebido"

   "Cash Account" "Caixa"

   "Changed»order" "Modificar"
   "Completed orders cannot be changed." "Os pedidos finalizados não podem ser modificados."
   "Save Changes" "Salvar modificações"

   "Total" "Total"
   "Total Price" "Preço total"

   ;phone & mixed.cljs
   "Call via IVR" "Chamada URA"
   "Call" "Ligar"
   "Calling..." "Ligando"
   "Delete Record" "Apagar registro"
   "Delete" "Apagar"
   "Cancel Deletion" "Anular cancelamento"
   "Wrong format" "Formato incorreto" ;;Update this line: "Ürünler hatalı girildi"

   ;Warehouse.cljs
   ;"Plase enter a name" "İsim girilmelidir"
   ;"Color" "Renk"
   ;"Notes" "Notlar"
   ;"Save" "Kaydet"
   ;"Notes" "Notlar"
   ;"Target Storage" "Hedef Depo"
   ;"Notes" "Notlar"
   ;"Save" "Kaydet"
   "Storage Name" "Nome de armazém"
   "Storage Type" "Tipo de armazém"
   "Vehicle" "Veículo"
   "Warehouse" "Depósito"
   "Storage Manager" "Gerente de armazém"
   "Source Storage" "Armazém de origem"
   "Target Storage" "Armazém de destino"
   "Source" "Origem"
   "Target" "Destino"
   "Items" "Itens"
   "Add New Storage" "Adicionar novo armazém"
   "Add Items" "Adicionar itens"
   "Move Items" "Mover itens"
   "Remove Items" "Remover itens"
   "Move items to another storage" "Mover os itens para outro armazém"
   "Storage" "Armazém"
   "Move" "Mover"

   ;Ledger.cljs
   ;"Source" "Kaynak"
   ;"Target" "Hedef"
   ;"Save" "Kaydet"
   "Saved" "Salvo"
   "This area is mandatory" "Esta área é obrigatória"
   "Please select" "Escolha, por favor"
   "Enter the value" "Insira o valor"
   "Add a transaction" "Adicionar uma transação"
   "Transaction reference" "Referência de transação"
   "Transaction date" "Data de transação"
   ;"Now" "Şimdi"
   "Value" "Valor"
   "Date" "Data"
   ;"Account" "Hesap"
   "Start date" "Data do início"
   "End date" "Data final"
   ;"Apply" "Uygula"
   "Transaction" "Transação"
   "Transaction Filter" "Filtro de transações"
   "Past 5 weeks" "Últimas 5 semanas"
   "Filtered transactions" "Transações filtradas"
   "New Transaction" "Nova transação"


   ;users.cljs
   ;"Carrier" "Plasiyer"
   "Username" "Nome do usuário"
   "Password" "Senha"
   "Manager" "Gerente"
   "Name" "Nome"
   "User" "Usuário"
   "Permissions" "Permissões"
   "Add a new account" "Adicionar uma nova conta"

   ;Time.cljs
   "January" "Janeiro"
   "February" "Fevereiro"
   "March" "Março"
   "April" "Abril"
   "May " "Maio"
   "June" "Junho"
   "July" "Julho"
   "August" "Agosto"
   "September" "Setembro"
   "October" "Outubro"
   "November" "Novembro"
   "December" "Dezembro"

   "Jan" "jan."
   "Feb" "fev."
   "Mar" "mar."
   "Apr" "abr."
   "May" "maio"
   "Jun" "jun."
   "Jul" "jul."
   "Agu" "ago."
   "Sep" "set."
   "Oct" "out."
   "Nov" "nov."
   "Dec" "dez."

   "Monday" "Segunda-feira"
   "Tuesday" "Terça-feira"
   "Wednesday" "Quarta-feira"
   "Thursday" "Quinta-feira"
   "Friday" "Sexta-feira"
   "Saturday" "Sábado"
   "Sunday" "Domingo"

   "minutes" "minutos"
   "hours" "horas"
   "days" "dias"
   "months" "meses"
   "ago" "atrás"
   "later" "depois"})

; END OF THE FILE
; Ignore everthing after this point

(def blocks
  {:settings-top
   [:<>
    [:h4 "Önemli Not:"]
    [:p "Türkçe içerik" [:strong " datanız kaybolur."] " Dropbox ile bağlanın"]
    [:p "Şunu kullanıyoruz " [:a {:href "https://remotestorage.io/"} "remotestorage.io"] " protokolle bağlanın."]]})
